# theme.toml template for a Hugo theme

name = "Static Kalbag Theme"
license = ""
licenselink = ""
description = "Laura’s custom theme"
homepage = "https://laurakalbag.com"
tags = []
features = []
min_version = 0.25

[author]
  name = "Laura Kalbag"
  homepage = "https://laurakalbag.com"
